name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libzip-dev libjpeg-dev openjdk-11-jdk unzip zip
        pip install --user buildozer cython

    - name: Build APK
      run: |
        ~/.local/bin/buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: turfexplorer-apk
        path: ~/.buildozer/android/platform/build/dists/*/*.apk # Update this path as needed
